CREATE TABLE dbo.CAD_KEEP_ALIVE
(
	ID_LOGIN INT NOT NULL PRIMARY KEY,
	DATA_LOGIN DATETIME NOT NULL,
	DATA_LAST_ALIVE DATETIME NOT NULL,

)

GO

CREATE NONCLUSTERED INDEX IX_CAD_KEEP_ALIVE_DATA_LAST_ALIVE ON dbo.CAD_KEEP_ALIVE (DATA_LAST_ALIVE)

GO

ALTER TABLE dbo.CAD_KEEP_ALIVE ADD LOGIN_COM_DISCADOR BIT NOT NULL

GO

ALTER TABLE dbo.CAD_KEEP_ALIVE ADD CENTRO_CUSTO INT

GO

CREATE TABLE [dbo].[CAD_LICENCA_NOVO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COD_TIPOLICENCA] [int] NULL,
	[QUANTIDADE_LOGINS] [int] NULL,
	[VALIDADE] [datetime] NULL,
	[ATIVA] [bit] NULL,
	[COD_RECUP_ADDED] [int] NULL,
	[HASH_LICENCA] [varchar](max) NULL,
	[DATA_INSERCAO] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[CAD_LICENCA_NOVO]  WITH CHECK ADD FOREIGN KEY([COD_TIPOLICENCA]) REFERENCES [dbo].[CAD_TIPOLICENCA] ([ID])

GO

CREATE TRIGGER dbo.TRG_LOGOUT_API_LICENCAS ON dbo.CAD_KEEP_ALIVE AFTER DELETE
AS
BEGIN
	INSERT INTO dbo.CAD_LOGOUT_CONTROLADOR (IDLOGIN, DATA_LOGOUT, TIPO_LOGOUT) SELECT DELETED.ID_LOGIN, GETDATE(), CAST(SESSION_CONTEXT(N'TIPO_LOGOUT') AS INT) FROM DELETED
END

GO

ALTER TABLE CAD_KEEP_ALIVE ENABLE TRIGGER TRG_LOGOUT_API_LICENCAS

GO

ALTER TABLE CAD_LOGOUT_CONTROLADOR ADD TIPO_LOGOUT TINYINT

GO

ALTER TABLE CAD_LOGOUT_CONTROLADOR ALTER COLUMN IDLOGIN INT NOT NULL

GO

ALTER TABLE CAD_LOGOUT_CONTROLADOR ADD PRIMARY KEY (IDLOGIN)